// DO NOT EDIT THIS FILE!!! IT WILL BE AUTOMATICALLY GENERATED FROM src/i18n
/*global systemDictionary:true */
'use strict';

systemDictionary = {
    "Add module": {                                  "en": "Add module",                                      "de": "Modul hinzufügen",                                "ru": "Добавить модуль",                                 "pt": "Adicionar módulo",                                "nl": "Module toevoegen",                                "fr": "Add module",                                      "it": "Aggiungi modulo",                                 "es": "Agregar módulo",                                  "pl": "Dodaj moduł",                                     "zh-cn": "添加模块"},
    "Additional npm modules:": {                     "en": "Additional npm modules:",                         "de": "Zusätzliche npm-Module:",                         "ru": "Дополнительные модули npm:",                      "pt": "Módulos adicionais npm:",                         "nl": "Extra npm-modules:",                              "fr": "Additional npm modules:",                         "it": "Moduli aggiuntivi di npm:",                       "es": "Módulos npm adicionales:",                        "pl": "Dodatkowe moduły npm:",                           "zh-cn": "额外的npm模块："},
    "Configuration file": {                          "en": "Configuration file",                              "de": "Konfigurationsdatei",                             "ru": "Файл конфигурации",                               "pt": "Arquivo de configuração",                         "nl": "Configuratiebestand",                             "fr": "Configuration file",                              "it": "File di configurazione",                          "es": "Archivo de configuración",                        "pl": "Plik konfiguracyjny",                             "zh-cn": "配置文件"},
    "Global Homebridge Config Directory Path": {     "en": "Global Homebridge Config Directory Path",         "de": "Globaler Homebridge-Konfigurationsverzeichnispfad", "ru": "Путь к каталогу Global Homebridge Config",        "pt": "Caminho global do diretório de configuração do Homebridge", "nl": "Wereldwijd Homebridge Config Directory-pad",      "fr": "Global Homebridge Config Directory Path",         "it": "Percorso globale della directory di configurazione di Homebridge", "es": "Ruta del directorio de Global Homebridge Config", "pl": "Ścieżka katalogu konfiguracji globalnej Homebridge", "zh-cn": "全局Homebridge配置目录路径"},
    "Global Homebridge Path": {                      "en": "Global Homebridge Path",                          "de": "Globaler Homebridge-Pfad",                        "ru": "Глобальный путь на мосту",                        "pt": "Caminho Global Homebridge",                       "nl": "Wereldwijd homebridge pad",                       "fr": "Global Homebridge Path",                          "it": "Percorso globale di Homebridge",                  "es": "Ruta Global Homebridge",                          "pl": "Global Homebridge Path",                          "zh-cn": "全局Homebridge路径"},
    "Main settings": {                               "en": "Main settings",                                   "de": "Haupteinstellungen",                              "ru": "Основные настройки",                              "pt": "Configurações principais",                        "nl": "Belangrijkste instellingen",                      "fr": "Réglages principaux",                             "it": "Impostazioni principali",                         "es": "Ajustes principales",                             "pl": "Ustawienia główne",                               "zh-cn": "主要设置"},
    "Module names": {                                "en": "Module names",                                    "de": "Modulnamen",                                      "ru": "Имена модулей",                                   "pt": "Nomes de módulos",                                "nl": "Module namen",                                    "fr": "Module names",                                    "it": "Nomi dei moduli",                                 "es": "Nombres de módulos",                              "pl": "Nazwy modułów",                                   "zh-cn": "模块名称"},
    "Use insecure Homebridge mode": {                "en": "Use insecure Homebridge mode",                    "de": "Verwenden Sie den unsicheren Homebridge-Modus",   "ru": "Использовать небезопасный режим моста",           "pt": "Use o modo Homebridge inseguro",                  "nl": "Gebruik de onveilige Homebridge-modus",           "fr": "Utilisez le mode Homebridge non sécurisé",        "it": "Utilizzare la modalità Homebridge non sicura",    "es": "Utilice el modo inseguro de Homebridge",          "pl": "Użyj niezabezpieczonego trybu Homebridge",        "zh-cn": "使用不安全的Homebridge模式"},
    "Value Polling Interval": {                      "en": "Value Polling Interval (sec)",                    "de": "Wertabfrageintervall (sec)",                      "ru": "Интервал опроса значений (sec)",                  "pt": "Intervalo de Polling de Valor (sec)",             "nl": "Value Polling Interval (sec)",                    "fr": "Intervalle d'interrogation de valeur (sec)",      "it": "Intervallo di polling del valore (sec)",          "es": "Intervalo de interrogación de valor (sec)",       "pl": "Okres odpytywania wartości (sec)",                "zh-cn": "轮询间隔（秒）"},
    "useGlobalHomebridge": {                         "en": "Use global Homebridge",                           "de": "Verwenden Sie globale Homebridge",                "ru": "Использовать глобальный Homebridge",              "pt": "Use Homebridge global",                           "nl": "Gebruik wereldwijde Homebridge",                  "fr": "useGlobalHomebridge",                             "it": "Usa Homebridge globale",                          "es": "Utilice Global Homebridge",                       "pl": "Użyj globalnego rozwiązania Homebridge",          "zh-cn": "使用全局Homebridge"},
    "wrapperConfig": {                               "en": "Wrapper configuration",                           "de": "Wrapper-Konfiguration",                           "ru": "Конфигурация Wrapper",                            "pt": "Configuração do invólucro",                       "nl": "Wrapper-configuratie",                            "fr": "wrapperConfig",                                   "it": "Configurazione wrapper",                          "es": "Configuración del contenedor",                    "pl": "Konfiguracja opakowania",                         "zh-cn": "包装配置"},
    "updateLibraries": {
        "en": "Update Homebridge Plugins from NPM",
        "de": "Aktualisieren Sie die Homebridge Plugins von NPM",
        "ru": "Обновление плагинов Homebridge от NPM",
        "pt": "Atualize Plugins Homebridge da NPM",
        "nl": "Update Homebridge-plugins van NPM",
        "fr": "Mettre à jour les plugins Homebridge à partir de NPM",
        "it": "Aggiorna i plugin Homebridge da NPM",
        "es": "Actualizar los complementos de Homebridge desde NPM",
        "pl": "Zaktualizuj wtyczki Homebridge z NPM",
        "zh-cn": "从NPM更新Homebridge插件"
    },
    "virtualCommandLine": {
        "en": "Homebridge Command line parameters",
        "de": "Homebridge Befehlszeilenparameter",
        "ru": "Homebridge Параметры командной строки",
        "pt": "Parâmetros da linha de comando do Homebridge",
        "nl": "Homebridge opdrachtregelparameters",
        "fr": "Paramètres de ligne de commande Homebridge",
        "it": "Parametri della riga di comando di Homebridge",
        "es": "Parámetros de línea de comandos de Homebridge",
        "pl": "Parametry linii poleceń Homebridge",
        "zh-cn": "Homebridge命令行参数"
    },
    "homebridgeMode": {
        "en": "Homebridge Adapter Mode",
        "de": "Homebridge-Adapter-Modus",
        "ru": "Режим адаптера домашнего моста",
        "pt": "Modo Adaptador Homebridge",
        "nl": "Homebridge Adapter-modus",
        "fr": "Mode adaptateur Homebridge",
        "it": "Modalità adattatore Homebridge",
        "es": "Modo de adaptador Homebridge",
        "pl": "Tryb adaptera mostka domowego",
        "zh-cn": "Homebridge适配器模式"
    },
    "selectOptionGlobal": {
        "en": "Global Mode (start a compatible global installed Homebridge)",
        "de": "Globaler Modus (Start eines kompatiblen global installierten Homebridge)",
        "ru": "Глобальный режим (запуск совместимого глобального установленного Homebridge)",
        "pt": "Modo Global (inicie um Homebridge global compatível e compatível)",
        "nl": "Globale modus (start een compatibele, wereldwijd geïnstalleerde Homebridge)",
        "fr": "Mode Global (démarrer un Homebridge global compatible installé)",
        "it": "Modalità globale (avvia un Homebridge installato globale compatibile)",
        "es": "Modo global (iniciar un homebridge global compatible instalado)",
        "pl": "Tryb globalny (uruchom kompatybilny globalny zainstalowany Homebridge)",
        "zh-cn": "全局模式（启动兼容的全球安装的Homebridge）"
    },
    "selectOptionWrapper": {
        "en": "Wrapper Mode (just run Homebridge Plugins in ioBroker)",
        "de": "Wrapper-Modus (nur Homebridge-Plugins in ioBroker ausführen)",
        "ru": "Режим Wrapper (просто запустите плагины Homebridge в ioBroker)",
        "pt": "Modo Wrapper (basta executar Plugins Homebridge no ioBroker)",
        "nl": "Wrapper-modus (voer gewoon homebridge-plug-ins in ioBroker uit)",
        "fr": "Mode Wrapper (il suffit de lancer les plugins Homebridge dans ioBroker)",
        "it": "Modalità wrapper (basta eseguire i plugin Homebridge in ioBroker)",
        "es": "Modo de contenedor (solo ejecute los complementos de Homebridge en ioBroker)",
        "pl": "Tryb wrappera (wystarczy uruchomić wtyczki Homebridge w ioBroker)",
        "zh-cn": "包装模式（只需在ioBroker中运行Homebridge插件）"
    },
    "selectOptionLocal": {
        "en": "Local Mode (Install a local Homebridge in ioBroker as Bridge)",
        "de": "Lokaler Modus (Installieren Sie eine lokale Homebridge in ioBroker als Bridge)",
        "ru": "Локальный режим (установите локальный Homebridge в ioBroker как Bridge)",
        "pt": "Modo Local (Instale um Homebridge local no ioBroker como Bridge)",
        "nl": "Lokale modus (installeer een lokale Homebridge in ioBroker als Bridge)",
        "fr": "Mode local (installer un Homebridge local dans ioBroker en tant que pont)",
        "it": "Modalità locale (installa un Homebridge locale in ioBroker come Bridge)",
        "es": "Modo local (instale un Homebridge local en ioBroker como puente)",
        "pl": "Tryb lokalny (zainstaluj lokalny mostek domowy w ioBroker as Bridge)",
        "zh-cn": "本地模式（在ioBroker中安装本地Homebridge作为Bridge）"
    }
};
